/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Utiles.Archivo;
import Utiles.Data;
import Utiles.Mensaje;
import Utiles.Selector;
import Utiles.Validar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author omar
 */
public class Importar_de_archivo extends javax.swing.JInternalFrame {
  DefaultTableModel model;
  /**
   * Creates new form Importar_de_archivo
   */
  public Importar_de_archivo() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jToolBar1 = new javax.swing.JToolBar();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jToggleButton1 = new javax.swing.JToggleButton();

    setClosable(true);
    setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    setMaximizable(true);
    setResizable(true);
    setTitle("Importar de un archivo");

    jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null},
        {null, null, null, null}
      },
      new String [] {
        "Title 1", "Title 2", "Title 3", "Title 4"
      }
    ));
    jTable1.setCellSelectionEnabled(false);
    jTable1.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(jTable1);

    jToolBar1.setRollover(true);

    jButton1.setText("Archivo");
    jButton1.setFocusable(false);
    jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jToolBar1.add(jButton1);

    jButton2.setText("Nombre Columna");
    jButton2.setFocusable(false);
    jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });
    jToolBar1.add(jButton2);

    jToggleButton1.setText("Guardar");
    jToggleButton1.setFocusable(false);
    jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jToggleButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jToolBar1.add(jToggleButton1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
      .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    llenarTabla();
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    // TODO add your handling code here:
    cambiarCabezera();
    
  }//GEN-LAST:event_jButton2ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JToolBar jToolBar1;
  // End of variables declaration//GEN-END:variables
  
  /**
   * LLenar la tabla con el contenido del archivo
   */
  private void llenarTabla(){
    // Importar datos de un archivo
    
    //abrir selector de archivos
    Selector selector = new Selector();
    
    String ruta = selector.selectorArchivo("CSV File", "csv", "CSV");
    String separador_cadena = Mensaje.mensage_entrada( "Ingresar el separador de cadenas." );
    
    System.out.println("ruta" + ruta);
    System.out.println("separador " + separador_cadena);
    
    //si se eligio el archivo
    if( ( ruta != null ) && (separador_cadena != null) ) {
        
      if( separador_cadena.equals("")) separador_cadena = " ";
      char separador = separador_cadena.charAt(0);

      Object[][] objeto;

      objeto = Data.arrayDatos( Archivo.leerArchivo(ruta), separador);

      int numColumnas = objeto[0].length;


      String[] titulos = new String[numColumnas];

      for(int i=0 ; i < numColumnas; i++){
        titulos[i]= Integer.toString(i);
      }
      model = new DefaultTableModel(objeto, titulos);
      this.jTable1.setModel(model);
      this.jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
      
      
      
    }else{
      //error al elegir el archivo
    }
    
    

  }
  //__________________________________________________________________
  
  private void cambiarCabezera(){
    //obtener numero columna seleccionada
    int numColum = this.jTable1.getSelectedColumn();
    //si no hay columna no se hace nada
    if( numColum != -1){
      //si no se creo el modelo no se hace nada
      if(model != null){
        //mostrar mensaje insertar nuevo nombre
        String nuevoNombre = Mensaje.mensage_entrada("Ingresar nuevo nombre "
                + "\n de la columna, no usar espacios");
        // si se cancelo no hacer nada, el nombre es null
        if( nuevoNombre != null){
          //si en nombre es una cadena vacia no hacer nada
          if( !nuevoNombre.equals("")){
            //Quitar espacios del nuevo nombre
            nuevoNombre = Validar.quitarEspacios(nuevoNombre);
            
            int numeroColumnas = this.jTable1.getColumnCount();
            
            String nombres[]= new String[numeroColumnas];
            
            for(int i=0 ; i < numeroColumnas ; i++){
              if( i != this.jTable1.getSelectedColumn() ){
                
                nombres[i] = model.getColumnName(i);
                
              }else{
                nombres[i] = nuevoNombre;
              }
            }

            model.setColumnIdentifiers(nombres);
            
            
          }else{
            Mensaje.mensaje_simple("Ese nombre no es valido.");
          }
          
        }
        
      }
      
    }else{
      Mensaje.mensaje_simple("Debe elegir una columna.");
    }
  }
}
